//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtxAgents.Client.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MtxAgents.Client.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمولة الوكيل.
        /// </summary>
        public static string AgentFeeAmount {
            get {
                return ResourceManager.GetString("AgentFeeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحساب.
        /// </summary>
        public static string lbl_AccName {
            get {
                return ResourceManager.GetString("lbl_AccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب .
        /// </summary>
        public static string lbl_AccNameNo {
            get {
                return ResourceManager.GetString("lbl_AccNameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string lbl_addBtn {
            get {
                return ResourceManager.GetString("lbl_addBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإضافة.
        /// </summary>
        public static string lbl_AddDate {
            get {
                return ResourceManager.GetString("lbl_AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة من حوالة سابقة.
        /// </summary>
        public static string lbl_addFromBtn {
            get {
                return ResourceManager.GetString("lbl_addFromBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string lbl_address {
            get {
                return ResourceManager.GetString("lbl_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكيل.
        /// </summary>
        public static string lbl_agent {
            get {
                return ResourceManager.GetString("lbl_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرع الوكيل.
        /// </summary>
        public static string lbl_agentBranch {
            get {
                return ResourceManager.GetString("lbl_agentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم فرع الوكيل.
        /// </summary>
        public static string lbl_agentBranchName {
            get {
                return ResourceManager.GetString("lbl_agentBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم فرع الوكيل.
        /// </summary>
        public static string lbl_agentBranchNo {
            get {
                return ResourceManager.GetString("lbl_agentBranchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الوكيل.
        /// </summary>
        public static string lbl_agentId {
            get {
                return ResourceManager.GetString("lbl_agentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الوكيل.
        /// </summary>
        public static string lbl_agentName {
            get {
                return ResourceManager.GetString("lbl_agentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوكيل.
        /// </summary>
        public static string lbl_agentNo {
            get {
                return ResourceManager.GetString("lbl_agentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الوكلاء.
        /// </summary>
        public static string lbl_agentNotes {
            get {
                return ResourceManager.GetString("lbl_agentNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكلاء.
        /// </summary>
        public static string lbl_agents {
            get {
                return ResourceManager.GetString("lbl_agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروع الوكلاء.
        /// </summary>
        public static string lbl_agentsBranches {
            get {
                return ResourceManager.GetString("lbl_agentsBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ كتابة .
        /// </summary>
        public static string lbl_amoutInChar {
            get {
                return ResourceManager.GetString("lbl_amoutInChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string lbl_amt {
            get {
                return ResourceManager.GetString("lbl_amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ الحوالة .
        /// </summary>
        public static string lbl_amt2 {
            get {
                return ResourceManager.GetString("lbl_amt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المبلغ.
        /// </summary>
        public static string lbl_amtData {
            get {
                return ResourceManager.GetString("lbl_amtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعتماد الحوالات .
        /// </summary>
        public static string lbl_ApprovalRem {
            get {
                return ResourceManager.GetString("lbl_ApprovalRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string lbl_AttachedDocument {
            get {
                return ResourceManager.GetString("lbl_AttachedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الواجهة الخلفية.
        /// </summary>
        public static string lbl_Backend {
            get {
                return ResourceManager.GetString("lbl_Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد.
        /// </summary>
        public static string lbl_Balance {
            get {
                return ResourceManager.GetString("lbl_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغطية رصيد.
        /// </summary>
        public static string lbl_balanceCoverage {
            get {
                return ResourceManager.GetString("lbl_balanceCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغرض من التغطية.
        /// </summary>
        public static string lbl_balanceCoverageٌReason {
            get {
                return ResourceManager.GetString("lbl_balanceCoverageٌReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب تغطية.
        /// </summary>
        public static string lbl_balanceCoverageRequest {
            get {
                return ResourceManager.GetString("lbl_balanceCoverageRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string lbl_balanceCoverageRequestNo {
            get {
                return ResourceManager.GetString("lbl_balanceCoverageRequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التغطية.
        /// </summary>
        public static string lbl_balanceCoverageRequestType {
            get {
                return ResourceManager.GetString("lbl_balanceCoverageRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المستفيد.
        /// </summary>
        public static string lbl_benfAddress {
            get {
                return ResourceManager.GetString("lbl_benfAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستفيد.
        /// </summary>
        public static string lbl_benfData {
            get {
                return ResourceManager.GetString("lbl_benfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستفيد.
        /// </summary>
        public static string lbl_benfName {
            get {
                return ResourceManager.GetString("lbl_benfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات للمستفيد.
        /// </summary>
        public static string lbl_benfNotes {
            get {
                return ResourceManager.GetString("lbl_benfNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف المستفيد.
        /// </summary>
        public static string lbl_benfPhone {
            get {
                return ResourceManager.GetString("lbl_benfPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string lbl_branch {
            get {
                return ResourceManager.GetString("lbl_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        public static string lbl_branches {
            get {
                return ResourceManager.GetString("lbl_branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفرع.
        /// </summary>
        public static string lbl_branchName {
            get {
                return ResourceManager.GetString("lbl_branchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفرع.
        /// </summary>
        public static string lbl_branchNo {
            get {
                return ResourceManager.GetString("lbl_branchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعراض.
        /// </summary>
        public static string lbl_browse {
            get {
                return ResourceManager.GetString("lbl_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسب اليوم .
        /// </summary>
        public static string lbl_byDay {
            get {
                return ResourceManager.GetString("lbl_byDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسب الشهر.
        /// </summary>
        public static string lbl_byMoath {
            get {
                return ResourceManager.GetString("lbl_byMoath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسب الفترة.
        /// </summary>
        public static string lbl_bypriod {
            get {
                return ResourceManager.GetString("lbl_bypriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string lbl_cancel {
            get {
                return ResourceManager.GetString("lbl_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصناديق.
        /// </summary>
        public static string lbl_Cashboxes {
            get {
                return ResourceManager.GetString("lbl_Cashboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string lbl_changePassword {
            get {
                return ResourceManager.GetString("lbl_changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدن.
        /// </summary>
        public static string lbl_cities {
            get {
                return ResourceManager.GetString("lbl_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string lbl_city {
            get {
                return ResourceManager.GetString("lbl_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة.
        /// </summary>
        public static string lbl_cityName {
            get {
                return ResourceManager.GetString("lbl_cityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المدينة.
        /// </summary>
        public static string lbl_cityNo {
            get {
                return ResourceManager.GetString("lbl_cityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string lbl_clientId {
            get {
                return ResourceManager.GetString("lbl_clientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string lbl_closeBtn {
            get {
                return ResourceManager.GetString("lbl_closeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصام العمولة.
        /// </summary>
        public static string lbl_CommissionDeduction {
            get {
                return ResourceManager.GetString("lbl_CommissionDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string lbl_confirmPassword {
            get {
                return ResourceManager.GetString("lbl_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصادقة ارصدة الحسابات .
        /// </summary>
        public static string lbl_ConformingStatemen {
            get {
                return ResourceManager.GetString("lbl_ConformingStatemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطابق.
        /// </summary>
        public static string lbl_Conformity {
            get {
                return ResourceManager.GetString("lbl_Conformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاعتماد .
        /// </summary>
        public static string lbl_Conformity_date {
            get {
                return ResourceManager.GetString("lbl_Conformity_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطابقة الى تاريخ .
        /// </summary>
        public static string lbl_Conformity_to_date {
            get {
                return ResourceManager.GetString("lbl_Conformity_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ.
        /// </summary>
        public static string lbl_copy {
            get {
                return ResourceManager.GetString("lbl_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دائن.
        /// </summary>
        public static string lbl_Credit {
            get {
                return ResourceManager.GetString("lbl_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاصة بين الصناديق.
        /// </summary>
        public static string lbl_crossTreasuriesExch {
            get {
                return ResourceManager.GetString("lbl_crossTreasuriesExch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاصة بين الصناديق.
        /// </summary>
        public static string lbl_CrossTreasuriesExchanges {
            get {
                return ResourceManager.GetString("lbl_CrossTreasuriesExchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        public static string lbl_currencies {
            get {
                return ResourceManager.GetString("lbl_currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string lbl_currency {
            get {
                return ResourceManager.GetString("lbl_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملة الحوالة.
        /// </summary>
        public static string lbl_currency2 {
            get {
                return ResourceManager.GetString("lbl_currency2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز العملة.
        /// </summary>
        public static string lbl_currencyCode {
            get {
                return ResourceManager.GetString("lbl_currencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العملة.
        /// </summary>
        public static string lbl_currencyName {
            get {
                return ResourceManager.GetString("lbl_currencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العملة.
        /// </summary>
        public static string lbl_currencyNo {
            get {
                return ResourceManager.GetString("lbl_currencyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية.
        /// </summary>
        public static string lbl_currentPassword {
            get {
                return ResourceManager.GetString("lbl_currentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابات العملاء.
        /// </summary>
        public static string lbl_CustomerAccounts {
            get {
                return ResourceManager.GetString("lbl_CustomerAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويل الى حساب عميل.
        /// </summary>
        public static string lbl_CustomerAccountsTransfer {
            get {
                return ResourceManager.GetString("lbl_CustomerAccountsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قص.
        /// </summary>
        public static string lbl_cut {
            get {
                return ResourceManager.GetString("lbl_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string lbl_date {
            get {
                return ResourceManager.GetString("lbl_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت والتاريخ.
        /// </summary>
        public static string lbl_dateTime {
            get {
                return ResourceManager.GetString("lbl_dateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدين.
        /// </summary>
        public static string lbl_Debit {
            get {
                return ResourceManager.GetString("lbl_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string lbl_deleteBtn {
            get {
                return ResourceManager.GetString("lbl_deleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيداع الى حساب عميل.
        /// </summary>
        public static string lbl_Depositing {
            get {
                return ResourceManager.GetString("lbl_Depositing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيان.
        /// </summary>
        public static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفصيلي.
        /// </summary>
        public static string lbl_detailed {
            get {
                return ResourceManager.GetString("lbl_detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string lbl_detial {
            get {
                return ResourceManager.GetString("lbl_detial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المستفيد.
        /// </summary>
        public static string lbl_detialPAY {
            get {
                return ResourceManager.GetString("lbl_detialPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة.
        /// </summary>
        public static string lbl_direction {
            get {
                return ResourceManager.GetString("lbl_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرع الجهة.
        /// </summary>
        public static string lbl_directionBranch {
            get {
                return ResourceManager.GetString("lbl_directionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الجهة.
        /// </summary>
        public static string lbl_directionData {
            get {
                return ResourceManager.GetString("lbl_directionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستند.
        /// </summary>
        public static string lbl_doc {
            get {
                return ResourceManager.GetString("lbl_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string lbl_docNo {
            get {
                return ResourceManager.GetString("lbl_docNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سحب من حساب عميل.
        /// </summary>
        public static string lbl_Drawing {
            get {
                return ResourceManager.GetString("lbl_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbl_editBtn {
            get {
                return ResourceManager.GetString("lbl_editBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  بيع وشراء العملات.
        /// </summary>
        public static string lbl_Exchange_Transactions {
            get {
                return ResourceManager.GetString("lbl_Exchange_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسعار الصرف.
        /// </summary>
        public static string lbl_ExhanView {
            get {
                return ResourceManager.GetString("lbl_ExhanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string lbl_exit {
            get {
                return ResourceManager.GetString("lbl_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير إكسل.
        /// </summary>
        public static string lbl_ExportExcel {
            get {
                return ResourceManager.GetString("lbl_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير القالب.
        /// </summary>
        public static string lbl_exportExcelTemplate {
            get {
                return ResourceManager.GetString("lbl_exportExcelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإكسبرس.
        /// </summary>
        public static string lbl_expressNo {
            get {
                return ResourceManager.GetString("lbl_expressNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمولة.
        /// </summary>
        public static string lbl_fee {
            get {
                return ResourceManager.GetString("lbl_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمولة المركز.
        /// </summary>
        public static string lbl_fee2 {
            get {
                return ResourceManager.GetString("lbl_fee2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملة العمولة.
        /// </summary>
        public static string lbl_feeCurrency {
            get {
                return ResourceManager.GetString("lbl_feeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف.
        /// </summary>
        public static string lbl_file {
            get {
                return ResourceManager.GetString("lbl_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الخط.
        /// </summary>
        public static string lbl_fontSize {
            get {
                return ResourceManager.GetString("lbl_fontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غامق.
        /// </summary>
        public static string lbl_fontWeightBold {
            get {
                return ResourceManager.GetString("lbl_fontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غامق جداً.
        /// </summary>
        public static string lbl_fontWeightExtraBold {
            get {
                return ResourceManager.GetString("lbl_fontWeightExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خفيف.
        /// </summary>
        public static string lbl_fontWeightLight {
            get {
                return ResourceManager.GetString("lbl_fontWeightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادي.
        /// </summary>
        public static string lbl_fontWeightNormal {
            get {
                return ResourceManager.GetString("lbl_fontWeightNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الواجهة الأمامية .
        /// </summary>
        public static string lbl_Frontend {
            get {
                return ResourceManager.GetString("lbl_Frontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إخفاء.
        /// </summary>
        public static string lbl_hide {
            get {
                return ResourceManager.GetString("lbl_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنتهاء.
        /// </summary>
        public static string lbl_idEndDate {
            get {
                return ResourceManager.GetString("lbl_idEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور الهوية.
        /// </summary>
        public static string lbl_idImages {
            get {
                return ResourceManager.GetString("lbl_idImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإصدار.
        /// </summary>
        public static string lbl_idIssueDate {
            get {
                return ResourceManager.GetString("lbl_idIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الإصدار.
        /// </summary>
        public static string lbl_idIssuePlace {
            get {
                return ResourceManager.GetString("lbl_idIssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم  الهوية.
        /// </summary>
        public static string lbl_IdNumber {
            get {
                return ResourceManager.GetString("lbl_IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم  الهوية للمستفيد.
        /// </summary>
        public static string lbl_IdNumber1 {
            get {
                return ResourceManager.GetString("lbl_IdNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم  الهوية للمرسل.
        /// </summary>
        public static string lbl_IdNumber2 {
            get {
                return ResourceManager.GetString("lbl_IdNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الهوية.
        /// </summary>
        public static string lbl_idType {
            get {
                return ResourceManager.GetString("lbl_idType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  انوع الهوية للمستفيد.
        /// </summary>
        public static string lbl_idType1 {
            get {
                return ResourceManager.GetString("lbl_idType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    نوع الهوية للمرسل .
        /// </summary>
        public static string lbl_idType2 {
            get {
                return ResourceManager.GetString("lbl_idType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقق.
        /// </summary>
        public static string lbl_importedRemCheck {
            get {
                return ResourceManager.GetString("lbl_importedRemCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة ملف الإستيراد.
        /// </summary>
        public static string lbl_ImportFileFormat {
            get {
                return ResourceManager.GetString("lbl_ImportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد من ملف.
        /// </summary>
        public static string lbl_importFromFile {
            get {
                return ResourceManager.GetString("lbl_importFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد حوالة.
        /// </summary>
        public static string lbl_importRem {
            get {
                return ResourceManager.GetString("lbl_importRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  كل المستخدمين .
        /// </summary>
        public static string lbl_ٍinUserBtn {
            get {
                return ResourceManager.GetString("lbl_ٍinUserBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string lbl_Language {
            get {
                return ResourceManager.GetString("lbl_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string lbl_login {
            get {
                return ResourceManager.GetString("lbl_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string lbl_logout {
            get {
                return ResourceManager.GetString("lbl_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرعة شريط الأخبار.
        /// </summary>
        public static string lbl_marqueeSpeed {
            get {
                return ResourceManager.GetString("lbl_marqueeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرعة شريط الأخبار.
        /// </summary>
        public static string lbl_marqueeSpeed1 {
            get {
                return ResourceManager.GetString("lbl_marqueeSpeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهر.
        /// </summary>
        public static string lbl_month {
            get {
                return ResourceManager.GetString("lbl_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيدي.
        /// </summary>
        public static string lbl_myBalance {
            get {
                return ResourceManager.GetString("lbl_myBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string lbl_newPassword {
            get {
                return ResourceManager.GetString("lbl_newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب مستخدم جديد.
        /// </summary>
        public static string lbl_newUserRequest {
            get {
                return ResourceManager.GetString("lbl_newUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string lbl_no {
            get {
                return ResourceManager.GetString("lbl_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  بدون رصيد افتتاحي.
        /// </summary>
        public static string lbl_Nobalance {
            get {
                return ResourceManager.GetString("lbl_Nobalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مطابق.
        /// </summary>
        public static string lbl_NonConformity {
            get {
                return ResourceManager.GetString("lbl_NonConformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظة.
        /// </summary>
        public static string lbl_note {
            get {
                return ResourceManager.GetString("lbl_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الملاحظة.
        /// </summary>
        public static string lbl_noteDate {
            get {
                return ResourceManager.GetString("lbl_noteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملاحظة.
        /// </summary>
        public static string lbl_noteNo {
            get {
                return ResourceManager.GetString("lbl_noteNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد الإدارة.
        /// </summary>
        public static string lbl_noteReply {
            get {
                return ResourceManager.GetString("lbl_noteReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string lbl_notes {
            get {
                return ResourceManager.GetString("lbl_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير متصل.
        /// </summary>
        public static string lbl_Offline {
            get {
                return ResourceManager.GetString("lbl_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        public static string lbl_ok {
            get {
                return ResourceManager.GetString("lbl_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متصل.
        /// </summary>
        public static string lbl_Online {
            get {
                return ResourceManager.GetString("lbl_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العملية .
        /// </summary>
        public static string lbl_operation_no {
            get {
                return ResourceManager.GetString("lbl_operation_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب .
        /// </summary>
        public static string lbl_OrderDate {
            get {
                return ResourceManager.GetString("lbl_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string lbl_orderNo {
            get {
                return ResourceManager.GetString("lbl_orderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        public static string lbl_passwordNotMatched {
            get {
                return ResourceManager.GetString("lbl_passwordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لصق.
        /// </summary>
        public static string lbl_paste {
            get {
                return ResourceManager.GetString("lbl_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الصرف .
        /// </summary>
        public static string lbl_PaymentNote {
            get {
                return ResourceManager.GetString("lbl_PaymentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشبكات - استلام حوالة.
        /// </summary>
        public static string lbl_PayRemExternalSystem {
            get {
                return ResourceManager.GetString("lbl_PayRemExternalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التلفون.
        /// </summary>
        public static string lbl_phone {
            get {
                return ResourceManager.GetString("lbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        public static string lbl_printBtn {
            get {
                return ResourceManager.GetString("lbl_printBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شراء عملة.
        /// </summary>
        public static string lbl_Purchase_CurrenciesExchange {
            get {
                return ResourceManager.GetString("lbl_Purchase_CurrenciesExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غرض التحويل.
        /// </summary>
        public static string lbl_purposeOfRem {
            get {
                return ResourceManager.GetString("lbl_purposeOfRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستلام.
        /// </summary>
        public static string lbl_receiveBtn {
            get {
                return ResourceManager.GetString("lbl_receiveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام حوالة.
        /// </summary>
        public static string lbl_receiveRem {
            get {
                return ResourceManager.GetString("lbl_receiveRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستلام حوالة.
        /// </summary>
        public static string lbl_reciveRem {
            get {
                return ResourceManager.GetString("lbl_reciveRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string lbl_refreshBtn {
            get {
                return ResourceManager.GetString("lbl_refreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضلاً أدخل المبلغ لإعتماد الحوالة.
        /// </summary>
        public static string lbl_remAmountconfirm {
            get {
                return ResourceManager.GetString("lbl_remAmountconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد مبلغ الحوالة.
        /// </summary>
        public static string lbl_remAmountConfirmation {
            get {
                return ResourceManager.GetString("lbl_remAmountConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الجهة.
        /// </summary>
        public static string lbl_remDirectionType {
            get {
                return ResourceManager.GetString("lbl_remDirectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حوالات الشبكات   .
        /// </summary>
        public static string lbl_RemExternalSystem {
            get {
                return ResourceManager.GetString("lbl_RemExternalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استيراد الحوالات.
        /// </summary>
        public static string lbl_remImport {
            get {
                return ResourceManager.GetString("lbl_remImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة استيراد الحوالات.
        /// </summary>
        public static string lbl_remImportFormat {
            get {
                return ResourceManager.GetString("lbl_remImportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحوالات.
        /// </summary>
        public static string lbl_remittances {
            get {
                return ResourceManager.GetString("lbl_remittances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحوالة.
        /// </summary>
        public static string lbl_remNo {
            get {
                return ResourceManager.GetString("lbl_remNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير الحوالات.
        /// </summary>
        public static string lbl_ٌRemReport {
            get {
                return ResourceManager.GetString("lbl_ٌRemReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمدة.
        /// </summary>
        public static string lbl_remStatusApproved {
            get {
                return ResourceManager.GetString("lbl_remStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغية.
        /// </summary>
        public static string lbl_remStatusCancelled {
            get {
                return ResourceManager.GetString("lbl_remStatusCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديدة.
        /// </summary>
        public static string lbl_remStatusNew {
            get {
                return ResourceManager.GetString("lbl_remStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير معتمدة.
        /// </summary>
        public static string lbl_remStatusNotApproved {
            get {
                return ResourceManager.GetString("lbl_remStatusNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدفوعة.
        /// </summary>
        public static string lbl_remStatusPaid {
            get {
                return ResourceManager.GetString("lbl_remStatusPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاهزة للدفع.
        /// </summary>
        public static string lbl_remStatusReadyTobePaid {
            get {
                return ResourceManager.GetString("lbl_remStatusReadyTobePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معكوسة.
        /// </summary>
        public static string lbl_remStatusReversed {
            get {
                return ResourceManager.GetString("lbl_remStatusReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرسلة.
        /// </summary>
        public static string lbl_remStatusSent {
            get {
                return ResourceManager.GetString("lbl_remStatusSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الرد.
        /// </summary>
        public static string lbl_replyDate {
            get {
                return ResourceManager.GetString("lbl_replyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التقرير.
        /// </summary>
        public static string lbl_ReportName {
            get {
                return ResourceManager.GetString("lbl_ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        public static string lbl_Reports {
            get {
                return ResourceManager.GetString("lbl_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات.
        /// </summary>
        public static string lbl_requests {
            get {
                return ResourceManager.GetString("lbl_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عكس  بيع وشراء عملة .
        /// </summary>
        public static string lbl_ReverseCurrenciesExchange {
            get {
                return ResourceManager.GetString("lbl_ReverseCurrenciesExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيع عملة .
        /// </summary>
        public static string lbl_Sal_CurrenciesExchange {
            get {
                return ResourceManager.GetString("lbl_Sal_CurrenciesExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbl_saveBtn {
            get {
                return ResourceManager.GetString("lbl_saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string lbl_searchBtn {
            get {
                return ResourceManager.GetString("lbl_searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث عن حوالة .
        /// </summary>
        public static string lbl_searchByNamePhoneBtn {
            get {
                return ResourceManager.GetString("lbl_searchByNamePhoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث عن حوالة.
        /// </summary>
        public static string lbl_searchForRem {
            get {
                return ResourceManager.GetString("lbl_searchForRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string lbl_sendBtn {
            get {
                return ResourceManager.GetString("lbl_sendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المرسل.
        /// </summary>
        public static string lbl_senderAddress {
            get {
                return ResourceManager.GetString("lbl_senderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المرسل.
        /// </summary>
        public static string lbl_senderData {
            get {
                return ResourceManager.GetString("lbl_senderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المرسل.
        /// </summary>
        public static string lbl_senderName {
            get {
                return ResourceManager.GetString("lbl_senderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف المرسل.
        /// </summary>
        public static string lbl_senderPhone {
            get {
                return ResourceManager.GetString("lbl_senderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجمالي عمولة الارسال.
        /// </summary>
        public static string lbl_sendFee {
            get {
                return ResourceManager.GetString("lbl_sendFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال ملاحظة.
        /// </summary>
        public static string lbl_sendNote {
            get {
                return ResourceManager.GetString("lbl_sendNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال طلب تسجيل.
        /// </summary>
        public static string lbl_sendPcRegReq {
            get {
                return ResourceManager.GetString("lbl_sendPcRegReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال حوالة.
        /// </summary>
        public static string lbl_sendRem {
            get {
                return ResourceManager.GetString("lbl_sendRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشبكات - ارسال حوالة.
        /// </summary>
        public static string lbl_sendRemEXtarnalSystem {
            get {
                return ResourceManager.GetString("lbl_sendRemEXtarnalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان السيرفر.
        /// </summary>
        public static string lbl_serverUrl {
            get {
                return ResourceManager.GetString("lbl_serverUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string lbl_state {
            get {
                return ResourceManager.GetString("lbl_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف حساب.
        /// </summary>
        public static string lbl_StatmentReport {
            get {
                return ResourceManager.GetString("lbl_StatmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string lbl_status {
            get {
                return ResourceManager.GetString("lbl_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزامنة.
        /// </summary>
        public static string lbl_syncBtn {
            get {
                return ResourceManager.GetString("lbl_syncBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات النظام.
        /// </summary>
        public static string lbl_systemSettings {
            get {
                return ResourceManager.GetString("lbl_systemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث النظام.
        /// </summary>
        public static string lbl_systemUpdate {
            get {
                return ResourceManager.GetString("lbl_systemUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعابير البديبة.
        /// </summary>
        public static string lbl_TermCurrencyAgntView {
            get {
                return ResourceManager.GetString("lbl_TermCurrencyAgntView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي.
        /// </summary>
        public static string lbl_Total {
            get {
                return ResourceManager.GetString("lbl_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجمالي المبلغ.
        /// </summary>
        public static string lbl_Total_amt {
            get {
                return ResourceManager.GetString("lbl_Total_amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجمالي الكلي.
        /// </summary>
        public static string lbl_Total2 {
            get {
                return ResourceManager.GetString("lbl_Total2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  غرض  التحويل .
        /// </summary>
        public static string lbl_transferReason {
            get {
                return ResourceManager.GetString("lbl_transferReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستند .
        /// </summary>
        public static string lbl_type {
            get {
                return ResourceManager.GetString("lbl_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراجع.
        /// </summary>
        public static string lbl_undoBtn {
            get {
                return ResourceManager.GetString("lbl_undoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث البيانات الأساسية.
        /// </summary>
        public static string lbl_updateMainData {
            get {
                return ResourceManager.GetString("lbl_updateMainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدام الوضع الليلي.
        /// </summary>
        public static string lbl_useDarkTheme {
            get {
                return ResourceManager.GetString("lbl_useDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string lbl_username {
            get {
                return ResourceManager.GetString("lbl_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون القيمة رقمية.
        /// </summary>
        public static string lbl_valueMustBeNumber {
            get {
                return ResourceManager.GetString("lbl_valueMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال قيمة للحقل.
        /// </summary>
        public static string lbl_valueRequired {
            get {
                return ResourceManager.GetString("lbl_valueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإصدار.
        /// </summary>
        public static string lbl_version {
            get {
                return ResourceManager.GetString("lbl_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string lbl_viewBtn {
            get {
                return ResourceManager.GetString("lbl_viewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة.
        /// </summary>
        public static string lbl_Year {
            get {
                return ResourceManager.GetString("lbl_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string lbl_yes {
            get {
                return ResourceManager.GetString("lbl_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد إضافة حوالة  جديده من هذه الحوالة .
        /// </summary>
        public static string msg_addFromConfirmation {
            get {
                return ResourceManager.GetString("msg_addFromConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبالغ بالعملية المحلية  ريال يمني اقل من 2000 ريال هل تريد الإستمرار؟   .
        /// </summary>
        public static string msg_AmontLest {
            get {
                return ResourceManager.GetString("msg_AmontLest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تكتمل عملية الإستيراد. هل تريد إلغاء العملية؟.
        /// </summary>
        public static string msg_cancelRemImport {
            get {
                return ResourceManager.GetString("msg_cancelRemImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الإضافة من حوالة بتاريخ يوم سابق.
        /// </summary>
        public static string msg_canntAddFromOldRem {
            get {
                return ResourceManager.GetString("msg_canntAddFromOldRem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال بيانات للبحث.
        /// </summary>
        public static string msg_enterDataToSearch {
            get {
                return ResourceManager.GetString("msg_enterDataToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اسم المستخدم وكلمة المرور.
        /// </summary>
        public static string msg_exception1001 {
            get {
                return ResourceManager.GetString("msg_exception1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        public static string msg_exception1002 {
            get {
                return ResourceManager.GetString("msg_exception1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تسجيل هذا الجهاز.
        /// </summary>
        public static string msg_exception1003 {
            get {
                return ResourceManager.GetString("msg_exception1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهاز مسجّل مسبقاً.
        /// </summary>
        public static string msg_exception1004 {
            get {
                return ResourceManager.GetString("msg_exception1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلب تسجيل الجهاز مسبقاً.
        /// </summary>
        public static string msg_exception1005 {
            get {
                return ResourceManager.GetString("msg_exception1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفض طلب تسجيل الجهاز.
        /// </summary>
        public static string msg_exception1006 {
            get {
                return ResourceManager.GetString("msg_exception1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يحب ادخال اسم المستخدم أو كلمة المرور.
        /// </summary>
        public static string msg_exception1007 {
            get {
                return ResourceManager.GetString("msg_exception1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إيقاف الحساب.
        /// </summary>
        public static string msg_exception1008 {
            get {
                return ResourceManager.GetString("msg_exception1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مصرح للمستخدم بالوصول لهذا المورد.
        /// </summary>
        public static string msg_exception1009 {
            get {
                return ResourceManager.GetString("msg_exception1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الجلسة.
        /// </summary>
        public static string msg_exception1010 {
            get {
                return ResourceManager.GetString("msg_exception1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنتهت الجلسة مسبقاً. لا يمكن إلغاء صلاحياتها.
        /// </summary>
        public static string msg_exception1011 {
            get {
                return ResourceManager.GetString("msg_exception1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء صلاحية الجلسة مسبقاً.
        /// </summary>
        public static string msg_exception1012 {
            get {
                return ResourceManager.GetString("msg_exception1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير قادر على الإتصال.
        /// </summary>
        public static string msg_exception5003 {
            get {
                return ResourceManager.GetString("msg_exception5003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string msg_exception5100 {
            get {
                return ResourceManager.GetString("msg_exception5100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم  احتساب العمولة.
        /// </summary>
        public static string msg_FeeAmtNotEntered {
            get {
                return ResourceManager.GetString("msg_FeeAmtNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي إدخال بيانات جميع الحقول الإجبارية.
        /// </summary>
        public static string msg_fillAllMandatoryFields {
            get {
                return ResourceManager.GetString("msg_fillAllMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اسم المستخدم أو كملة المرور.
        /// </summary>
        public static string msg_invalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("msg_invalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستفيد او المرسل يجب ان يكون .
        /// </summary>
        public static string msg_name_length_chek {
            get {
                return ResourceManager.GetString("msg_name_length_chek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاطع او اكثر.
        /// </summary>
        public static string msg_name_length_chek2 {
            get {
                return ResourceManager.GetString("msg_name_length_chek2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة يجب أن لا تتضمن أو تساوي كلمة المرور القديمة.
        /// </summary>
        public static string msg_newPasswordContainsOld1 {
            get {
                return ResourceManager.GetString("msg_newPasswordContainsOld1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        public static string msg_operationSuccess {
            get {
                return ResourceManager.GetString("msg_operationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صحيحة.
        /// </summary>
        public static string msg_passwordNotCurrect {
            get {
                return ResourceManager.GetString("msg_passwordNotCurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة .
        /// </summary>
        public static string msg_passwordNotMatched {
            get {
                return ResourceManager.GetString("msg_passwordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم احتساب عمولة  للحوالة. هل تريد الإستمرار؟.
        /// </summary>
        public static string msg_PayFeeAmtNotEntered {
            get {
                return ResourceManager.GetString("msg_PayFeeAmtNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلب تسجيل مسبقاً. يرجى التواصل مع مسؤول النظام للإعتماد.
        /// </summary>
        public static string msg_pcAlreadyRegButNotAprvd {
            get {
                return ResourceManager.GetString("msg_pcAlreadyRegButNotAprvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الجهاز غير مرخص. يرجى إرسال طلب ترخيص.
        /// </summary>
        public static string msg_pcNotRegistered {
            get {
                return ResourceManager.GetString("msg_pcNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهاز مسجل بنجاح.
        /// </summary>
        public static string msg_pcRegistered {
            get {
                return ResourceManager.GetString("msg_pcRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم رفض طلب الترخيص.
        /// </summary>
        public static string msg_pcRegistrationRejected {
            get {
                return ResourceManager.GetString("msg_pcRegistrationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلب التسجيل بنجاح.
        /// </summary>
        public static string msg_pcRegistrationRequestSent {
            get {
                return ResourceManager.GetString("msg_pcRegistrationRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم إدخال عمولة الإرسال. هل تريد الإستمرار؟.
        /// </summary>
        public static string msg_sendFeeNotEntered {
            get {
                return ResourceManager.GetString("msg_sendFeeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حصل خطأ في احتساب العمولة. يرجى المحاولة مرة أخرى.
        /// </summary>
        public static string msg_unableToGetFee {
            get {
                return ResourceManager.GetString("msg_unableToGetFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الخروج؟.
        /// </summary>
        public static string msg_unExitChanges {
            get {
                return ResourceManager.GetString("msg_unExitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حصل خطا غير معروف.
        /// </summary>
        public static string msg_unkonwErro {
            get {
                return ResourceManager.GetString("msg_unkonwErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد تغيرات لم يتم حفظها. هل تريد التراجع؟.
        /// </summary>
        public static string msg_unSavedChanges {
            get {
                return ResourceManager.GetString("msg_unSavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الوكيل غير موجود.
        /// </summary>
        public static string msg_wrongAgenCode {
            get {
                return ResourceManager.GetString("msg_wrongAgenCode", resourceCulture);
            }
        }
    }
}
